name1 = String.new('eugene')
name2 = String.new('choi')
puts(name1.reverse())
puts(name2.reverse())
puts(name1.upcase())
puts(name1.size())
names = Array.new()
names.push('eugene')
names.push('choi')
puts(names)
puts(names.join(','))
